### ISSUE TITLE
can you teach me how to use it

### ISSUE THREAD

**Issue by wangruiqi-git** [Meroser/IPTV#1]

**Comment by Meroser** [comment]
1. Install live streaming software, such as Tivimate, Televizo, Perfect Player, DIYP, or TVbox. Tivimate is recommended.
2. Import live streaming sources by copying and pasting my live streaming subscription link into the software.
3. Import Electronic Program Guide (EPG).
Note: Please make sure you are in mainland China and have an IPv6 environment.
