### ISSUE TITLE
频道0个

### ISSUE THREAD

**Issue by zhendliu** [Meroser/IPTV#10]
自从你修复了cctv5+的那个问题后，现在我的软件苹果手机的aptv不能用了，添加后频道列表0个频道。之前好好的

**Comment by Meroser** [comment]
请使用这个地址：https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u

**Comment by Meroser** [comment]
> 请使用这个地址：https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u

我刚刚测试，aptv可以正常更新 165个频道

**Comment by zhendliu** [comment]
嗯，昨天的确是下载文件就不行了，刚这个链接可以用
