### ISSUE TITLE
TVBOX本地源

### ISSUE THREAD

**Issue by Hi-my-friends** [Meroser/IPTV#11]
Hi 大佬
请教一个问题。我尝试把直播源做到HTTP服务器，配置到TVBOX就能使用，但是把txt直播源文件放到电视盒子里面，配置clan://localhost/list.txt，直播源就不能用，我哪里起手不对么？

**Comment by Meroser** [comment]
请试下这个链接：https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV-tvbox.txt

**Comment by Meroser** [comment]
不太清楚了，我都是用的在线源http
