### ISSUE TITLE
央视的都播放不了

### ISSUE THREAD

**Issue by wellbeing-yang** [Meroser/IPTV#20]

**Comment by wellbeing-yang** [comment]
aptv可以打开 iplayer央视打不开

**Comment by Meroser** [comment]
应该是播放器的问题。也这边测试没问题的

**Comment by wellbeing-yang** [comment]
为什么呀 iplayer播放不了 aptb可以播放央视的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Meroser ***@***.***>
发送时间: Saturday, January 20, 2024 7:01:20 PM
收件人: Meroser/IPTV ***@***.***>
抄送: wellbeing-yang ***@***.***>; Author ***@***.***>
主题: Re: [Meroser/IPTV] 央视的都播放不了 (Issue #20)


应该是播放器的问题。也这边测试没问题的

―

**Comment by Meroser** [comment]
抱歉啊没用过 iplayer

**Comment by wellbeing-yang** [comment]
可能是有些播放器没有支持mp2解码
