### ISSUE TITLE
TVbox的源看不了

### ISSUE THREAD

**Issue by cloudpanl** [Meroser/IPTV#21]
在TVbox的直播源中填了如下地址，进入直播后，频道一直在切换，所有频道循环完了，没有一个能放的，是宽带的IP地址需要IPV6吗？还是只有开通了移动的IPTV服务才能使用这些源？
链接[TVbox]：https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/IPTV-tvbox.txt

**Comment by Meroser** [comment]
需要ipv6
