### ISSUE TITLE
我用的iptv.m3u文件导入iptv por软件但是很多频道看不成，忘解决。

### ISSUE THREAD

**Issue by maoyuyu** [Meroser/IPTV#23]
特别是中央好几个台加载不出来。能不能分享处可以有最新的m3u文件下载地址，这样手机端就可以直接操作了。

**Comment by Meroser** [comment]
https://raw.fgit.cf/Meroser/IPTV/main/IPTV.m3u，建议使用在线订阅的方式。这样可以实时更新

**Comment by Meroser** [comment]
https://raw.fgit.cf/Meroser/IPTV/main/IPTV.m3u

**Comment by Meroser** [comment]
建议使用订阅的方式导入，这样就可以实时更新

**Comment by maoyuyu** [comment]
> 建议使用订阅的方式导入，这样就可以实时更新

福利吧过来的，你的这个咪咕看NBA很好用，所以一直用你的源，电视端用的tivmate，直接导入M3U文件很好用，但是链接电视端得一个个用遥控器设置太麻烦，希望能提供更新的m3u的文件下载，谢谢了，话说你的福利吧帖子我怎么找不到了，想在帖子上直接联系你反馈问题。

**Comment by maoyuyu** [comment]
> https://raw.fgit.cf/Meroser/IPTV/main/IPTV.m3u

这个链接怎么直接下载成m3u文件？

**Comment by Meroser** [comment]
右键另存为

**Comment by mwsgly** [comment]
江苏电信，最新的ipv6源还是无法观看

**Comment by twedu** [comment]
北京卫视很卡

**Comment by leo280705022** [comment]
播放源都是断线的，只有22个是正常在线的！根本用不了呀！望处理
![Uploading 1111.png…]()
