### ISSUE TITLE
节目预告源

### ISSUE THREAD

**Issue by lxf1009** [Meroser/IPTV#24]
我用的tivimate2.8，节目预告源用的地址1，地址1比地址2快一点，但是还是有些时候自动更新会失败，我要手动更新几次才行，请问怎么能解决这个麻烦，需要改个DNS吗？还有回放和时移是不是和节目源有关？好像不能用。

**Comment by Meroser** [comment]
根据你的描述，那可能是app的问题，可以尝试换个版本，如2.1.5，两个地址都出问题的可能性比较低。
回放和时移我没玩过，不知道支不支持。

**Comment by lxf1009** [comment]
好的，我试试别的版本。
