### ISSUE TITLE
更新后xTeVe导入EPG出现错误

### ISSUE THREAD

**Issue by locoy-123** [Meroser/IPTV#25]
XML syntax error on line 1150: invalid XML name: 1
提示这个导入不了 原来是可行的

**Comment by locoy-123** [comment]
不知道是否有解决方案 谢谢

**Comment by Meroser** [comment]
感谢反馈，原因为1150行，湘西剿匪记 <1> 这一条中的<>为xml文件特殊字符导致。稍后修正该错误

**Comment by locoy-123** [comment]
感谢感谢！ 源好用又稳定 关键还在epg 大佬威武！
