### ISSUE TITLE
大佬，能在地方栏目加上广东珠江吗

### ISSUE THREAD

**Issue by mnbvcxzz1375** [Meroser/IPTV#26]

**Comment by Meroser** [comment]
如果找到稳定直播源会考虑加入。

**Comment by danielzi** [comment]
同求加入广东的频道

**Comment by cloudpanl** [comment]
https://www.gdtv.cn/tvChannelDetail/43 这里有一些广东频道

**Comment by Meroser** [comment]
> https://www.gdtv.cn/tvChannelDetail/43 这里有一些广东频道

这个不行，是按照流量失效的无法有效抓取
