### ISSUE TITLE
cctv5频道电视端异常

### ISSUE THREAD

**Issue by yehuzhucha** [Meroser/IPTV#29]
老师好，很感谢您的付出，但不知道是我电视的原因还是什么，cctv5和咪咕4k直播2都无法正常播放，目前尝试过tivimate和televizo都不可以，想请问有什么解决方法吗大佬

**Comment by Meroser** [comment]
应该是你电视的配置问题。没办法解码导致

**Comment by surhide** [comment]
同样问题 很奇怪 就这两个频道 只要点到就会先是 IllegalStateException错误，然后所有频道[DecoderInitializationException]错误，只能重启app

**Comment by yehuzhucha** [comment]
> 同样问题 很奇怪 就这两个频道 只要点到就会先是 IllegalStateException错误，然后所有频道[DecoderInitializationException]错误，只能重启app

应该是他们是4k的问题

**Comment by surhide** [comment]
> > 同样问题 很奇怪 就这两个频道 只要点到就会先是 IllegalStateException错误，然后所有频道[DecoderInitializationException]错误，只能重启app
> 
> 应该是他们是4k的问题

应该不是  因为其他几个4k频道都没问题  难道这两个网站解码特殊？
