### ISSUE TITLE
能否把AUTO tvxml.py脚本发我一份

### ISSUE THREAD

**Issue by kongjun0** [Meroser/IPTV#3]
95346618@qq.com

**Comment by Meroser** [comment]
https://github.com/Meroser/IPTV/blob/9c495d1de1570ca2d7e1bfb0f29e15a10db91360/Auto-TVxml.py api不适用于github action，所以我现在是放在vps上执行。

**Comment by kongjun0** [comment]
我自己有服务器，ubuntu和debian ,能发我一份吗？我最近在学习爬虫，想研究下。
