### ISSUE TITLE
为什么全都播放失败啊，kodi播放器

### ISSUE THREAD

**Issue by jiangqiang1996** [Meroser/IPTV#32]
![Uploading 17069241861958086638688581355735.jpg…]()

**Comment by hhht110** [comment]
因为这个.M3U文件都下载不下来 自然看不到源地址，所以就无法播放。。我试了半天le .

**Comment by hhht110** [comment]
那就不清楚了。反正我这里根本下载不下来。。不知道什么情况

**Comment by wxjdsj** [comment]
https://raw.fgit.cf/这个站挂了

> 因为这个.M3U文件都下载不下来 自然看不到源地址，所以就无法播放。。我试了半天le .

raw.fgit.cf应该是这个站挂了

**Comment by wxjdsj** [comment]
https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u

可以试试

**Comment by hhht110** [comment]
> [wxjdsj](/wxjdsj)

我靠可以了啊而且 【potp播放器】能看 8K都能看哈哈哈感谢感谢

**Comment by hhht110** [comment]
> [https://raw.fgit.cf/这个站挂了](https://raw.fgit.cf/%E8%BF%99%E4%B8%AA%E7%AB%99%E6%8C%82%E4%BA%86)
> 
> > 因为这个.M3U文件都下载不下来，自然看不到源地址，所以就无法播放。。我试了半天了.
> 
> raw.fgit.cf应该是这个站挂了

可以了 可以了 非常感谢非常感谢哈哈。 404大佬这个也不错 哈哈
