### ISSUE TITLE
翡翠台和明珠台特别卡

### ISSUE THREAD

**Issue by woaidianqian** [Meroser/IPTV#34]
翡翠台和明珠台特别卡，其他台都很完美，就是这两个台不太行，我的是联通宽带。

**Comment by Meroser** [comment]
TVB这三个台没有稳定的源，在考虑移除了

**Comment by xiaodusx1** [comment]
这几个好像不是ip6的

**Comment by xiaodusx1** [comment]
> TVB这三个台没有稳定的源，在考虑移除了

卡是卡点，好过没有吧。除非有稳定的源代替。

**Comment by abnerlam** [comment]
挂梯子没有特别卡
