### ISSUE TITLE
大佬，raw.fgit.cf貌似挂了

### ISSUE THREAD

**Issue by notatmore13** [Meroser/IPTV#35]
所以频道都打不开了

**Comment by yehuzhucha** [comment]
可以使用
https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u
内容一样，都是这位老师的

**Comment by Meroser** [comment]
感谢反馈，确实是挂了。可以用上面这个地址

**Comment by wintekk** [comment]
> 可以使用 https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u 内容一样，都是这位老师的

这个地址我订阅不了
