### ISSUE TITLE
为啥我添加后全部都超时啊？

### ISSUE THREAD

**Issue by CruiseYuGH** [Meroser/IPTV#36]
苏州移动网络。大神求解

**Comment by Meroser** [comment]
是没有办法添加直播源，还是直播源能添加，频道无法播放。前者的话，使这个地址：https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u如果是后者，请确保你有IPv6，

**Comment by shruru** [comment]
Apple 
TV + APTV ，和楼主一样。家里宽带上网正常，但添加地址后，所有直播源都能看到。但全部显示”超时“。请问 ipv6 是什么，怎么设置呢？谢谢

**Comment by peqing** [comment]
大佬没有IPV6咋搞啊！
我添加厚，打开TVBOX直播全部快速自动换台，应该是源不能播放一直闪这换台，
