### ISSUE TITLE
纯小白，有没有哪位大佬能来个具体的使用说明

### ISSUE THREAD

**Issue by gongsunmolan** [Meroser/IPTV#37]
纯小白，有没有哪位大佬能来个具体的使用说明

**Comment by gongsunmolan** [comment]
这个格式的：EPG文件地址[tvxml格式]

**Comment by Meroser** [comment]
这个文件适用于支持xml格式的IPTV播放器，tivimate,televizo,APTV,ntPlayer。如果你使用的是以上四款APP，使用我的m3u格式直播源会自动导入tvxml文件，无需额外设置。直播源内置了两个，其中tvxml为稳定版,tvxml-test.gz为详情版，可按需选择。

**Comment by stupidchou** [comment]
这个现在源弄过之后，电视节目单是有了，但是内容出不来是为啥呢？是被和谐了？

**Comment by stupidchou** [comment]
![IMG_3191](https://github.com/Meroser/IPTV/assets/17778075/80bc0bb7-b4f2-4240-a9b3-f425155ac6b9)
![IMG_3192](https://github.com/Meroser/IPTV/assets/17778075/0c389bd4-e36f-40d3-bea8-4dd3a39d35ee)
![IMG_3193](https://github.com/Meroser/IPTV/assets/17778075/1831efc0-3dbb-4ea0-8d29-0e28f973ec09)

**Comment by kennylbj** [comment]
我这也是这个情况，节目单有，但是视频播放失败
