### ISSUE TITLE
大佬是不是挂了，怎么现在电视一直显示让更新流博

### ISSUE THREAD

**Issue by stupidchou** [Meroser/IPTV#42]
大佬是不是挂了，怎么现在电视一直显示让更新流博

**Comment by wxjdsj** [comment]
https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u

用这个链接

**Comment by stupidchou** [comment]
> https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV.m3u

电视频道源用的就是这个
![IMG_3191](https://github.com/Meroser/IPTV/assets/17778075/814b3c13-4167-4680-aa29-25de639afc31)
![IMG_3192](https://github.com/Meroser/IPTV/assets/17778075/39bbdfa2-d038-40b3-8b06-1d0c743587b4)
![IMG_3193](https://github.com/Meroser/IPTV/assets/17778075/b485351a-960a-469c-8d6f-39bc0e5b120d)
这是为啥呢

**Comment by stupidchou** [comment]
![IMG_3191](https://github.com/Meroser/IPTV/assets/17778075/99a75ad8-9b69-4302-bf21-1da3180a991e)
![IMG_3192](https://github.com/Meroser/IPTV/assets/17778075/3cc2e6c4-82bc-4e53-9943-227797bef23d)
![IMG_3193](https://github.com/Meroser/IPTV/assets/17778075/91cf476e-d55d-4e88-9b79-8bb5d9e6a7d2)

**Comment by stupidchou** [comment]
![image](https://github.com/Meroser/IPTV/assets/17778075/989ee46d-f04c-4dbd-b86e-8e9199e06763)

**Comment by sunjiaheng7825** [comment]
我也是这样，为什么呢？资源不行了吗

**Comment by wxjdsj** [comment]
我这没问题，网的问题吧

**Comment by sunjiaheng7825** [comment]
查看下对应的网络，是不是不支持ipv6
