### ISSUE TITLE
EPG更新不了

### ISSUE THREAD

**Issue by shuimuoo7** [Meroser/IPTV#45]
大佬。我两个EPG都无法更新预告了，IPV6源

**Comment by Meroser** [comment]
你用的哪个地址？

**Comment by shuimuoo7** [comment]
稳定版两个地址都不行

**Comment by lxf1009** [comment]
@Meroser 建议把这个项目自动同步到gitee上，然后用那边生成的地址，电视上更新特别丝滑，我自己有个小的m3u就是这么弄的。

**Comment by wxjdsj** [comment]
> @Meroser 建议把这个项目自动同步到gitee上，然后用那边生成的地址，电视上更新特别丝滑，我自己有个小的m3u就是这么弄的。

我觉得没必要，这东西不要想着造福普罗大众，如果大家都能用了，那离被ban也就不远了
