### ISSUE TITLE
我自己有服务器和环境，能发我Py脚本吗

### ISSUE THREAD

**Issue by kongjun0** [Meroser/IPTV#5]
我自己有服务器，ubuntu和debian ,能发我一份吗？我最近在学习爬虫，想研究下。95346618@qq.com

**Comment by Meroser** [comment]
我在上个issue回复你了呀

**Comment by Meroser** [comment]
https://github.com/Meroser/IPTV/blob/2051da528db6834e23fe93fc67b7b8dda05d1287/Auto-TVxml.py

**Comment by Meroser** [comment]
有问题可在此issue继续交流

**Comment by kongjun0** [comment]
好的，谢谢！能帮忙写个从http://www.epg.huan.tv/henan/channel_index爬取数据脚本，可以通过ID来获取需要的频道。

**Comment by Meroser** [comment]
> 好的，谢谢！能帮忙写个从[http://www.epg.huan.tv/henan/channel_index爬取数据脚本，可以通过ID来获取需要的频道。](http://www.epg.huan.tv/henan/channel_index%E7%88%AC%E5%8F%96%E6%95%B0%E6%8D%AE%E8%84%9A%E6%9C%AC%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87ID%E6%9D%A5%E8%8E%B7%E5%8F%96%E9%9C%80%E8%A6%81%E7%9A%84%E9%A2%91%E9%81%93%E3%80%82)

这个站不错哦，还有节目介绍。可惜数据不是json格式，不过也可以弄。等我得空吧，最近好多事。
