### ISSUE TITLE
湖南地方台好像都用不了

### ISSUE THREAD

**Issue by 1522754841** [Meroser/IPTV#50]
金鹰卡通能用，其他的一直加载不出来

**Comment by Meroser** [comment]
用的酒店源，失效了。明天修复

**Comment by Meroser** [comment]
可以先用这个https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/mgtv/main/mgtv.m3u

**Comment by Meroser** [comment]
已修复
