### ISSUE TITLE
咕咪频道能不能整合一下

### ISSUE THREAD

**Issue by maoyuyu** [Meroser/IPTV#52]
平时爱看NBA，一直用你的源，发现有很多咕咪直播台一直是广告也没有实质性内容，能不能把这些源精简掉。还有就是ipv6直播源是不是直播延迟个5到10秒？

**Comment by Meroser** [comment]
那些现在是广告循环播放的台在重大体育活动时候会播放赛事。IPv6直播源会有一定程度的暂时，不止IPv6，运营商IPTV的单播也会有延时。

**Comment by maoyuyu** [comment]
> 那些现在是广告循环播放的台在重大体育活动时候会播放赛事。IPv6直播源会有一定程度的延时，不止IPv6，运营商IPTV的单播也会有延时。

那可不可以把平时经常播放的咕咪频道移动到前列，平时广告的频道放到后列，这样找台就不用长时间翻找了！

**Comment by Meroser** [comment]
> > 那些现在是广告循环播放的台在重大体育活动时候会播放赛事。IPv6直播源会有一定程度的延时，不止IPv6，运营商IPTV的单播也会有延时。
> 
> 那可不可以把平时经常播放的咕咪频道移动到前列，平时广告的频道放到后列，这样找台就不用长时间翻找了！

咪咕那个我平时没怎么关注，哪些台平时播放正常内容可以帮整理下吗 我重新调整一下顺序

**Comment by maoyuyu** [comment]
> > > 那些现在是广告循环播放的台在重大体育活动时候会播放赛事。IPv6直播源会有一定程度的延时，不止IPv6，运营商IPTV的单播也会有延时。
> > 
> > 那可不可以把平时经常播放的咕咪频道移动到前列，平时广告的频道放到后列，这样找台就不用长时间翻找了！
> 
> 咪咕那个我平时没怎么关注，哪些台平时播放正常内容可以帮整理下吗 我重新调整一下顺序

我平时看NBA，寻找需要看的台几乎要翻阅整个咕咪列表找，到底哪个频道播放确实不好找。

**Comment by ashsteins** [comment]
日本电视台可以多添加到国际频道里，我分享了60多个台的源，已测试
https://iptvcat.com/japan__2

**Comment by vikii0210** [comment]
最新的咪咕id重合，导致每次刷新只有一个台出现，

**Comment by pixeldin** [comment]
> > > 广告循环播放的台在重大体育活动的时候会播放赛事。IPv6直播源会有一定程度的延迟，不仅IPv6，运营商IPTV的单播也有延迟。
> > 
> > 
> > 那可不能把平时经常播放的咕咪频道移动到前列，平时广告的频道放在后列，
> 
> 自己一个个看，然后有喜欢的频道，直接放到频道收藏夹就可以了

他这个咪咕频道源的序号和当天播放的比赛好像不是固定的，蛋疼的地方在于比如今天咪咕08播放比赛，明天有可能变成咪咕11，频道是不确定的。所以每次查看当天比赛相当于要40个咪咕频道遍历重新找一次，不知道有什么优化方式。

**Comment by pixeldin** [comment]
> > > 那些现在是广告循环播放的台在重大体育活动时候会播放赛事。IPv6直播源会有一定程度的延时，不止IPv6，运营商IPTV的单播也会有延时。
> > 
> > 
> > 那可不可以把平时经常播放的咕咪频道移动到前列，平时广告的频道放到后列，这样找台就不用长时间翻找了！
> 
> 咪咕那个我平时没怎么关注，哪些台平时播放正常内容可以帮整理下吗 我重新调整一下顺序

他这个咪咕频道源的序号和当天播放的比赛不是固定的，蛋疼的地方在于比如今天咪咕08播放比赛，明天有可能变成咪咕11，就是说哪些频道在播放赛事是不确定的。所以每次查看当天比赛相当于要40个咪咕频道遍历重新找一次，不知道有什么优化方式。

**Comment by vikii0210** [comment]
其实有一些规律，比如08每天上午的时候一定会直播一场NBA， 平时CBA直播11，25，28，33，37，概率比较高的台。 但是大部分确实还是要遍历一遍，   还有一些30多号的台爱直播一些五大联赛的足球。

**Comment by YIFang0926** [comment]
请问你们现在都用什么源看NBA？
