### ISSUE TITLE
详情版的EPG CCTV5 节目单信息错误

### ISSUE THREAD

**Issue by inkss** [Meroser/IPTV#58]
节目单信息：
<img width="1280" alt="24-02-27_011840" src="https://github.com/Meroser/IPTV/assets/31947043/55f1f733-6e8b-4810-8d8d-dc4e6d0d3137">

正确的节目单信息：
<img width="837" alt="24-02-27_011943" src="https://github.com/Meroser/IPTV/assets/31947043/e7a7e846-2999-45a9-b89c-b82f59833a96">

EPG 地址中给出的节目单实际为 **CCTV4欧洲** 的节目信息：
<img width="830" alt="24-02-27_012159" src="https://github.com/Meroser/IPTV/assets/31947043/3d456abf-a921-484d-8ac4-f74b00faacf0">

-------

希望更正，🙇‍

**Comment by Meroser** [comment]
已修正
