### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by vxiaonanv** [Meroser/IPTV#6]
怎么使用M3U 直接POTPLAYER或者tivimate无法播放

**Comment by Meroser** [comment]
你是不是不具备ipv6环境？potplayer要把m3u文件下载下来才可以，tivimate可以直接订阅。注意如果你没有科学上网环境是点击源列表中的链接右键复制链接。

**Comment by vxiaonanv** [comment]
> 你是不是不具备ipv6环境？potplayer要把m3u文件下载下来才可以，tivimate可以直接订阅。注意如果你没有科学上网环境是点击源列表中的链接右键复制链接。

谢谢提醒。已解决。可以看了。方便加VX吗？方便的话发我邮箱。谢谢 zechen0626@outlook.com
