### ISSUE TITLE
联通网络晚上所有台播放卡顿问题

### ISSUE THREAD

**Issue by 1098880928aa** [Meroser/IPTV#61]
家里1000M的宽带在晚上观看IPTV卡顿（白天正常），晚上播放1秒就缓冲

家庭网络环境是联通，光猫桥接+路由拨号

经测试晚上用手机联通流量播放一样卡顿，但换成移动手机流量播放不卡顿，电视连接手机移动流量热点也不卡顿

在群里讨论这个问题，有朋友说有可能是直播源是移动源，在联通网络中会有这种问题

**Comment by Meroser** [comment]
可能是这个原因，我们的直播源IPv6来自移动。建议有条件的话使用当地的运营商组播源

**Comment by fuuhoo** [comment]
> 可能是这个原因，我们的直播源IPv6来自移动。建议有条件的话使用当地的运营商组播源

请问下组播源要怎么用，需要开通iptv吗，或者给个科普链接
