### ISSUE TITLE
没有频道显示

### ISSUE THREAD

**Issue by skyblue0511** [Meroser/IPTV#62]
大概两周前用APTV看IPTV,显示“当前配置不含有任何频道”，用了IPTV的源都是这个结果。家里网络是支持IPV6。看其他的IPV6可以正常播放。
![1709340183123275102866809581813](https://github.com/Meroser/IPTV/assets/47215435/46cfb515-3a47-4364-bea5-d2ac72bcbc4c)
![17093402111944528514703827685307](https://github.com/Meroser/IPTV/assets/47215435/f65e5248-f161-43a4-9a70-fec2caded7f8)

**Comment by Meroser** [comment]
可以尝试该地址：https://cdn.jsdelivr.net/gh/Meroser/IPTV@main/IPTV.m3u

**Comment by skyblue0511** [comment]
这个地址可以，谢谢。
