### ISSUE TITLE
关于咪咕直播赛事的频道顺序的优化

### ISSUE THREAD

**Issue by pixeldin** [Meroser/IPTV#67]
咪咕频道源这个集成功能非常实用，体育爱好者福音，感谢贡献者的付出。
可惜的是每次咪咕频道源的频道序号和当天播放的比赛好像不是固定的，比如今天咪咕08在播放比赛，明天有可能变成咪咕11，就是说每一天哪个频道在播放nba是不确定的(因此无法提前收藏频道序号)。所以每次查看当天比赛相当于要在遥控器把40个咪咕频道遍历重新找一次，记下正在播放比赛的频道是哪几个，不知道有什么优化方式建议。

**Comment by 1eexk** [comment]
可以看到咪咕直播的中超？
