### ISSUE TITLE
大佬，突然间移出了，遇到什么问题了吗？

### ISSUE THREAD

**Issue by zhendliu** [Meroser/IPTV#69]
大佬，突然间移出了，遇到什么问题了吗？

**Comment by ZhangTizo** [comment]
同问

**Comment by kenziao2022** [comment]
什么情况，突然没了

**Comment by ZhangTizo** [comment]
我找了半天终于找到能用的流畅的m3u了，真难...
有需要的加V：tz215vip，免费分享
顺带问一下大佬是什么情况不做了，如果是资金问题我们都可以赞助的，咱不是用不起运营商的机顶盒，而是瞎捣鼓来体验生活更有性价比，嘻嘻

**Comment by stevenjtx** [comment]
啥情况这是

**Comment by sbzhaopeng** [comment]
有没有交流群呀

**Comment by dreamPis** [comment]
啥清空  突然删了

**Comment by langzizhui** [comment]
有谁fork了吗？发一下啊

**Comment by 654850695** [comment]
同问，怎么全部移除了，猝不及防。。

**Comment by xQhaha** [comment]
怎么删库了？

**Comment by suuny816** [comment]
有人拿这里的源去卖钱

**Comment by xQhaha** [comment]
> 有人拿这里的源去卖钱

卖钱就有点过分了。

**Comment by 654850695** [comment]
> 有人拿这里的源去卖钱

真有这样的🐶dog啊……

**Comment by kenziao2022** [comment]
> 有人拿这里的源去卖钱

太狗了

**Comment by airpeng66** [comment]
可以了这个免费好用的源 又凉了

**Comment by xiaopebaka** [comment]
太难了 好不容易找到这么好用的源 大佬没有交流群吗

**Comment by watcher2023** [comment]
好不容易有这么好的源……就没了

**Comment by depo0097** [comment]
大佬快回来吧想你

**Comment by koogg** [comment]
首页那里去找到之前 fork了的源码，再fork一份到自己仓库，然后用自己的地址就能看了，只是没有节目预告，需要自己折腾。

**Comment by chenbide** [comment]
几天前才发现这么棒的源 怎么突然就删了

**Comment by max0530** [comment]
> 首页那里去找到之前 fork了的源码，再fork一份到自己仓库，然后用自己的地址就能看了，只是没有节目预告，需要自己折腾。

fork了也是remove的状态啊

**Comment by 654850695** [comment]
> > 首页那里去找到之前 fork了的源码，再fork一份到自己仓库，然后用自己的地址就能看了，只是没有节目预告，需要自己折腾。
> 
> fork了也是remove的状态啊
 删除之前fork了才行

**Comment by koogg** [comment]
> > 首页那里去找到之前 fork了的源码，再fork一份到自己仓库，然后用自己的地址就能看了，只是没有节目预告，需要自己折腾。
> 
> fork了也是remove的状态啊

fork的是文件啊，地址也要换成自己仓库的地址，你地址不换还用原地址那肯定是找不到文件呀

**Comment by tangtang0929** [comment]
好可惜，好不容易找到一个稳定好用的，这就没了，大佬有群或其他更新的地方吗

**Comment by tangtang0929** [comment]
> > > 首页那里去找到之前 fork了的源码，再fork一份到自己仓库，然后用自己的地址就能看了，只是没有节目预告，需要自己折腾。
> > 
> > 
> > fork了也是remove的状态啊
> 
> fork的是文件啊，地址也要换成自己仓库的地址，你地址不换还用原地址那肯定是找不到文件呀。
> 
> ps：你要fork之前fork过的那些人的，不要fork这个，这个已经都没了，你fork肯定什么都没

fork了，但C5和C6的源不能看

**Comment by ddns6** [comment]
> 有人拿这里的源去卖钱

是哪个鳖孙儿干的？请附上出售途径或联系方式，干Ta.

**Comment by xiaodusx1** [comment]
可惜，感谢之前的付出。

**Comment by Ray20150109** [comment]
我说怎么突然用不起了，一上来就看到删库了，这么好的源，有的人真的太狗了。。。。虽然没用多久还是感谢大佬了

**Comment by shuimuoo7** [comment]
感谢大佬，这个过年电视看的挺好
