### ISSUE TITLE
直播源稳定更新吗

### ISSUE THREAD

**Issue by lhb8125** [Meroser/IPTV#9]
首先多谢大神， 有几个问题请教一下:
1. 直播源是否会稳定更新？
2. Ipv6直播源会比v4直播源更稳定吗？
3. 如何自己去查找直播源(v4&v6)?

**Comment by Meroser** [comment]
直播源会持续更新，有失效请issue；
ipv6源相对来说稳定；
至于如何自己查找直播源，请善用github搜索功能。
